[package]
name = "noriv"
version = "0.1.0"
edition = "2024"

[dependencies]
winapi = { version = "0.3", features = ["winuser", "windef", "winbase"] }

eframe = "0.24" # 或最新版本
cpal = "0.15"
midir = "0.9"
ringbuf = "0.3"
anyhow = "1.0"